# Generated by Django 3.1.5 on 2021-01-30 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisal', '0004_auto_20210127_2251'),
        ('Employee', '0003_employee_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='manager_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appraisal.manager'),
        ),
    ]
