# Generated by Django 3.1.5 on 2021-01-30 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_auto_20210130_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user_id',
        ),
    ]
