# Generated by Django 3.1.5 on 2021-01-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('appraisal_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Appraisal ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('perf_grade', models.CharField(choices=[('EXCELLENT', 'EXCELLENT'), ('GOOD', 'GOOD'), ('AVERAGE', 'AVERAGE'), ('POOR', 'POOR')], max_length=30, verbose_name='Performance Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Manager ID')),
                ('manager_name', models.CharField(max_length=30, verbose_name='Manager')),
            ],
        ),
    ]
