# Generated by Django 3.1.5 on 2021-01-26 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Appraisal', '0001_initial'),
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='employee_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.employee'),
        ),
    ]
