# Generated by Django 3.1.5 on 2021-01-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisal', '0002_appraisal_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appraisal',
            old_name='employee_ID',
            new_name='employee_name',
        ),
    ]
