# Generated by Django 3.1.5 on 2021-01-27 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisal', '0003_auto_20210127_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appraisal',
            old_name='employee_name',
            new_name='employee_ID',
        ),
    ]
