# Generated by Django 3.1.5 on 2021-01-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisal', '0004_auto_20210127_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='employee_id',
            field=models.IntegerField(default=None),
        ),
    ]
