# Generated by Django 3.1.5 on 2021-01-31 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisal', '0005_manager_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='employee_id',
            new_name='employee_ID',
        ),
    ]
